version: '3.9'

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring:

services:

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - monitoring
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

    prometheus:
      image: prom/prometheus
      volumes:
        - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus_data:/prometheus
      ports:
        - 9090:9090
      depends_on:
        - cadvisor
      networks:
        - monitoring
      deploy:
        placement:
          constraints:
            - node.role==manager
        restart_policy:
          condition: on-failure 

    node-exporter:
      image: prom/node-exporter
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
      ports:
        - 9100:9100
      networks:
        - monitoring
      deploy:
        mode: global
        restart_policy:
          condition: on-failure

    grafana:
      image: grafana/grafana
      volumes:
        - grafana_data:/var/lib/grafana
      ports:
       - 3000:3000
      depends_on:
        - prometheus
      networks:
        - monitoring
      user: "472"
      deploy:
        placement:
          constraints:
            - node.role==manager
        restart_policy:
          condition: on-failure
